ansible_runner/api/urls.py
"""Django API urlpatterns declaration for ansible_runner plugin."""

from nautobot.core.api import OrderedDefaultRouter

from ansible_runner.api import views

router = OrderedDefaultRouter()
# add the name of your api endpoint, usually hyphenated model name in plural, e.g. "my-model-classes"
router.register("ansibleprojects", views.AnsibleProjectsViewSet)


app_name = "ansible_runner-api"
urlpatterns = router.urls

ansible_runner/urls.py
"""Django urlpatterns declaration for ansible_runner plugin."""
from django.urls import path
from nautobot.extras.views import ObjectChangeLogView

from ansible_runner import models
from ansible_runner.views import ansibleprojects

urlpatterns = [
    # AnsibleProjects URLs
    path("ansibleprojects/", ansibleprojects.AnsibleProjectsListView.as_view(), name="ansibleprojects_list"),
    # Order is important for these URLs to work (add/delete/edit) to be before any that require uuid/slug
    path("ansibleprojects/add/", ansibleprojects.AnsibleProjectsCreateView.as_view(), name="ansibleprojects_add"),
    path("ansibleprojects/delete/", ansibleprojects.AnsibleProjectsBulkDeleteView.as_view(), name="ansibleprojects_bulk_delete"),
    path("ansibleprojects/edit/", ansibleprojects.AnsibleProjectsBulkEditView.as_view(), name="ansibleprojects_bulk_edit"),
    path("ansibleprojects/<slug:slug>/", ansibleprojects.AnsibleProjectsView.as_view(), name="ansibleprojects"),
    path("ansibleprojects/<slug:slug>/delete/", ansibleprojects.AnsibleProjectsDeleteView.as_view(), name="ansibleprojects_delete"),
    path("ansibleprojects/<slug:slug>/edit/", ansibleprojects.AnsibleProjectsEditView.as_view(), name="ansibleprojects_edit"),
    path(
        "ansibleprojects/<slug:slug>/changelog/",
        ObjectChangeLogView.as_view(),
        name="ansibleprojects_changelog",
        kwargs={"model": models.AnsibleProjects},
    ),
]

ansible_runner/models.py
"""Models for Ansible Runner."""

# Django imports
from django.db import models
from django.urls import reverse

# Nautobot imports
from nautobot.core.models import BaseModel
from nautobot.extras.models.change_logging import ChangeLoggedModel


# from nautobot.extras.utils import extras_features
# If you want to use the extras_features decorator please reference the following documentation
# https://nautobot.readthedocs.io/en/latest/plugins/development/#using-the-extras_features-decorator-for-graphql
# Then based on your reading you may decide to put the following decorator before the declaration of your class
# @extras_features("custom_fields", "custom_validators", "relationships", "graphql")

# If you want to choose a specific model to overload in your class declaration, please reference the following documentation:
# how to chose a database model: https://nautobot.readthedocs.io/en/stable/plugins/development/#database-models
class AnsibleProjects(BaseModel, ChangeLoggedModel):
    """Base model for Ansible Runner plugin."""

    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.CharField(max_length=200, blank=True)
    # additional model fields

    class Meta:
        """Meta class."""

        ordering = ["name"]

    def get_absolute_url(self):
        """Return detail view for AnsibleProjects."""
        return reverse("plugins:ansible_runner:ansibleprojects", args=[self.slug])

    def __str__(self):
        """Stringify instance."""
        return self.name

ansible_runner/forms.py
"""Forms for ansible_runner."""
from django import forms
from nautobot.utilities.forms import (
    BootstrapMixin,
    BulkEditForm,
    SlugField,
)

from ansible_runner import models


class AnsibleProjectsForm(BootstrapMixin, forms.ModelForm):
    """AnsibleProjects creation/edit form."""

    slug = SlugField()

    class Meta:
        """Meta attributes."""

        model = models.AnsibleProjects
        fields = [
            "name",
            "slug",
            "description",
        ]


class AnsibleProjectsBulkEditForm(BootstrapMixin, BulkEditForm):
    """AnsibleProjects bulk edit form."""

    pk = forms.ModelMultipleChoiceField(queryset=models.AnsibleProjects.objects.all(), widget=forms.MultipleHiddenInput)
    description = forms.CharField(required=False)

    class Meta:
        """Meta attributes."""

        nullable_fields = [
            "description",
        ]


class AnsibleProjectsFilterForm(BootstrapMixin, forms.ModelForm):
    """Filter form to filter searches."""

    q = forms.CharField(
        required=False,
        label="Search",
        help_text="Search within Name or Slug.",
    )
    name = forms.CharField(required=False, label="Name")
    slug = forms.CharField(required=False, label="Slug")

    class Meta:
        """Meta attributes."""

        model = models.AnsibleProjects
        # Define the fields above for ordering and widget purposes
        fields = [
            "q",
            "name",
            "slug",
            "description",
        ]

ansible_runner/api/views.py
"""API views for ansible_runner."""

from nautobot.core.api.views import ModelViewSet

from ansible_runner import filters, models

from ansible_runner.api import serializers


class AnsibleProjectsViewSet(ModelViewSet):  # pylint: disable=too-many-ancestors
    """AnsibleProjects viewset."""

    queryset = models.AnsibleProjects.objects.all()
    serializer_class = serializers.AnsibleProjectsSerializer
    filterset_class = filters.AnsibleProjectsFilterSet

ansible_runner/views/ansibleprojects.py
"""Views for AnsibleProjects."""

from nautobot.core.views import generic

from ansible_runner import filters, forms, models, tables


class AnsibleProjectsListView(generic.ObjectListView):
    """List view."""

    queryset = models.AnsibleProjects.objects.all()
    # These aren't needed for simple models, but we can always add
    # this search functionality.
    filterset = filters.AnsibleProjectsFilterSet
    filterset_form = forms.AnsibleProjectsFilterForm
    table = tables.AnsibleProjectsTable
    action_buttons = ("add", "export")


class AnsibleProjectsView(generic.ObjectView):
    """Detail view."""

    queryset = models.AnsibleProjects.objects.all()


class AnsibleProjectsCreateView(generic.ObjectEditView):
    """Create view."""

    model = models.AnsibleProjects
    queryset = models.AnsibleProjects.objects.all()
    model_form = forms.AnsibleProjectsForm


class AnsibleProjectsDeleteView(generic.ObjectDeleteView):
    """Delete view."""

    model = models.AnsibleProjects
    queryset = models.AnsibleProjects.objects.all()


class AnsibleProjectsEditView(generic.ObjectEditView):
    """Edit view."""

    model = models.AnsibleProjects
    queryset = models.AnsibleProjects.objects.all()
    model_form = forms.AnsibleProjectsForm


class AnsibleProjectsBulkDeleteView(generic.BulkDeleteView):
    """View for deleting one or more AnsibleProjects records."""

    queryset = models.AnsibleProjects.objects.all()
    table = tables.AnsibleProjectsTable


class AnsibleProjectsBulkEditView(generic.BulkEditView):
    """View for editing one or more AnsibleProjects records."""

    queryset = models.AnsibleProjects.objects.all()
    table = tables.AnsibleProjectsTable
    form = forms.AnsibleProjectsBulkEditForm

ansible_runner/templates/ansible_runner/ansibleprojects.html
{% extends 'base.html' %}
{% load buttons %}
{% load static %}
{% load custom_links %}
{% load helpers %}
{% load plugins %}

{% block title %}{{ object }}{% endblock %}



{% block header %}
<div class="row noprint">
	<div class="col-sm-8 col-md-9">
		<ol class="breadcrumb">
			<li><a href="{% url 'plugins:ansible_runner:ansibleprojects_list' %}">AnsibleProjects</a></li>
			<li>{{ object }}</li>
		</ol>
	</div>
	<div class="col-sm-4 col-md-3">
		<form action="{% url 'plugins:ansible_runner:ansibleprojects_list' %}"
			method="get">
			<div class="input-group">
				<input type="text" name="q" class="form-control" />
				<span class="input-group-btn">
					<button type="submit" class="btn btn-primary">
						<span class="mdi mdi-magnify" aria-hidden="true"></span>
					</button>
				</span>
			</div>
		</form>
	</div>
</div>
<div class="pull-right noprint">
	{% if perms.ansible_runner.change_ansibleprojects %}
	<a href="{% url 'plugins:ansible_runner:ansibleprojects_edit' slug=object.slug %}"
		class="btn btn-warning">
		<span class="mdi mdi-pencil" aria-hidden="true"></span> Edit
	</a>
	{% endif %}
	{% if perms.ansible_runner.delete_ansibleprojects %}
	<a href="{% url 'plugins:ansible_runner:ansibleprojects_delete' slug=object.slug %}"
		class="btn btn-danger">
		<span class="mdi mdi-trash-can-outline" aria-hidden="true"></span> Delete
	</a>
	{% endif %}
</div>
<h1>{{ object }}</h1>
{% include 'inc/created_updated.html' with obj=object %}
<div class="pull-right noprint">
	{% custom_links object %}
</div>
<ul class="nav nav-tabs">
	<li role="presentation" {% if not active_tab %} class="active" {% endif %}>
		<a href="{{ object.get_absolute_url }}">AnsibleProjects</a>
	</li>
	{% if perms.extras.view_objectchange %}
	<li role="presentation" {% if active_tab == 'changelog' %} class="active" {% endif %}>
		<a href="{% url 'plugins:ansible_runner:ansibleprojects_changelog' slug=object.slug %}">Change Log</a>
	</li>
	{% endif %}
</ul>
{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<strong>AnsibleProjects</strong>
			</div>
			<table class="table table-hover panel-body attr-table">
				<tr>
					<td>Name</td>
					<td>
						<a href="{{ object.get_absolute_url }}">{{ object.name }}</a>
					</td>
				</tr>
				<tr>
					<td>Description</td>
					<td>
						{{ object.description|placeholder }}
					</td>
				</tr>
			</table>
		</div>
		{% include 'inc/custom_fields_panel.html' %}
		{% include 'inc/relationships_panel.html' %}
		{% plugin_left_page object %}
	</div>
</div>
<div class="row">
	<div class="col-md-12">
		{% plugin_full_width_page object %}
	</div>
</div>
{% endblock %}